<?php
/**
 * Codilar Technologies Pvt. Ltd.
 * @package   Image360
 * @copyright   Copyright (c) 2016 Codilar. (http://www.codilar.com)
 * @author       Codilar Team
 **/
?>

<div class="fieldset-wrapper admin__fieldset-section">
    <div class="fieldset-wrapper-title" tabindex="-1">
        <strong class="title">
            <span><?php echo __('Images'); ?></span>
        </strong>
    </div>
    <div class="admin__fieldset-wrapper-content">
        <fieldset class="admin__fieldset">
            <?php echo $block->getChildHtml('image360_gallery'); ?>
        </fieldset>
    </div>
</div>
