<?php

/**
 * Codilar Technologies Pvt. Ltd.
 * @package   Image360
 * @copyright   Copyright (c) 2016 Codilar. (http://www.codilar.com)
 * @author       Codilar Team
 **/
?>
<p>
    <button onclick="setLocation('<?php  echo $block->getCleanImagesUrl() ?>')" type="button">
        <?php  echo __('Flush Image360 Images Cache') ?>
    </button>
    <span><?php echo __('Pregenerated Image360 images files') ?></span>
</p>
