<?php

/**
 * Codilar Technologies Pvt. Ltd.
 * @package   Image360
 * @copyright   Copyright (c) 2016 Codilar. (http://www.codilar.com)
 * @author       Codilar Team
 **/

/** @var $block \Magento\Backend\Block\Media\Uploader */
?>
<div id="<?php echo $block->getHtmlId() ?>" class="uploader"
    data-mage-init='{
        "Codilar_Image360/js/media-uploader" : {
            "maxFileSize": <?php echo $block->getFileSizeService()->getMaxFileSize() ?>,
            "maxWidth":<?php echo \Magento\Framework\File\Uploader::MAX_IMAGE_WIDTH ?> ,
            "maxHeight": <?php echo \Magento\Framework\File\Uploader::MAX_IMAGE_HEIGHT ?>
        }
    }'
>
    <div class="fileinput-button form-buttons button">
        <span><?php echo __('Browse Files...') ?></span>
        <input id="image360fileupload" type="file" name="<?php echo $block->getConfig()->getFileField() ?>"
            data-url="<?php  echo $block->getConfig()->getUrl() ?>" multiple="multiple" />
    </div>
    <div class="clear"></div>
    <script id="<?php echo $block->getHtmlId() ?>-template" type="text/x-magento-template" data-template="image360-uploader">
        <div id="<%- data.id %>" class="file-row">
            <span class="file-info"><%- data.name %> (<%- data.size %>)</span>
            <div class="progressbar-container">
                <div class="progressbar upload-progress" style="width: 0%;"></div>
            </div>
            <div class="clear"></div>
        </div>
    </script>
</div>
